### ISSUE TITLE
Enable/Disable Scheduler Support via an Environment Variable

### ISSUE THREAD

**Issue by jesusbrat** [symptoma/activemq#13]
It would be great to have the ability to enable schedulerSupport via an environment variable. 
This would require updating the `<broker ...>` tag in the **conf/activemq.xml** to include `schedulerSupport="true"`
```
<broker xmlns="http://activemq.apache.org/schema/core" brokerName="localhost" dataDirectory="${activemq.data}">
change to
<broker xmlns="http://activemq.apache.org/schema/core" 
      brokerName="localhost" dataDirectory="${activemq.data}" schedulerSupport="true" >
```
This would allow messages to be scheduled and/or have a deliveryDelay.

Thank you for your project and thank you in advance for considering this request.

**Comment by tholu** [comment]
@jesusbrat Great idea! Thanks to @samholton for the fast implementation. Will include it in the next release.
