### ISSUE TITLE
Kahadb

### ISSUE THREAD

**Issue by oalimerko** [symptoma/activemq#15]
where is kahadb located and if it is growing how do handle the size of it?

**Comment by tholu** [comment]
See https://activemq.apache.org/kahadb

**Comment by oalimerko** [comment]
> See https://activemq.apache.org/kahadb

i mean in docker image world,in onprem it's clear

**Comment by tholu** [comment]
@oalimerko It's the same, just inside the Docker container 😉  The host needs to have enough disk space to handle the size.
