### ISSUE TITLE
Update ActiveMQ to 5.18.2

### ISSUE THREAD

**Issue by wimdeblauwe** [symptoma/activemq#16]
Would be nice to have the latest version 5.18.2 available as docker image.

Release notes: https://activemq.apache.org/activemq-5018002-release

**Comment by tholu** [comment]
@wimdeblauwe That would be nice indeed. Released and [published](https://hub.docker.com/r/symptoma/activemq).

**Comment by wimdeblauwe** [comment]
That was fast. Thank you!
