### ISSUE TITLE
how to configure JMX settings for metrics and create Grafana dashboard with Prometheus

### ISSUE THREAD

**Issue by rahulmr** [symptoma/activemq#17]
Is it possible to get metrics from ActiveMQ which can be monitored using Prometheus and then a Grafana dashboard is created to display these metrics

[Here](https://www.metricfire.com/blog/architecture-and-monitoring-apache-activemq-with-grafana) is the tutorial which I am trying to follow but not sure how to do it in proper way.

Kindly, direct me to proper resources or provide some hints.

Thanks in advance!!!

**Comment by tholu** [comment]
@rahulmr I'm afraid this is out-of-scope for this project.
