### ISSUE TITLE
Readme refers to non-existing ACTIVEMQ_DISALLOW_WEBCONSOLE

### ISSUE THREAD

**Issue by AndriyKalashnykov** [symptoma/activemq#19]
Replace ACTIVEMQ_DISALLOW_WEBCONSOLE wtih an actual option name

**Comment by tholu** [comment]
Fixed in [7838043](https://github.com/symptoma/activemq/commit/783804394bc452910d6f3683fe9a21dda3168c1d), thanks for reporting!
