### ISSUE TITLE
ActiveMQ 5.16.0 with JDK11

### ISSUE THREAD

**Issue by imranrazakhan** [symptoma/activemq#2]
HI,

Have you tested docker image of ActiveMQ 5.16.0 with JDK11?

**Comment by tholu** [comment]
The docker image uses `openjdk:8-jre-alpine`. Why would you need JDK11 here?

**Comment by tholu** [comment]
In the meantime, the latest version uses `azul/zulu-openjdk-alpine:13-jre`.
