### ISSUE TITLE
ActiveMQ Security

### ISSUE THREAD

**Issue by sconstro** [symptoma/activemq#20]
ActiveMQ security (JMS) is not enabled even if a ACTIVEMQ_USERNAME is set.

How to reproduce:
Start the container: docker run --rm -it -e ACTIVEMQ_PASSWORD=x -e ACTIVEMQ_USERNAME=q symptoma/activemq:latest
Go inside container : docker exec -it CONTAINER_ID  sh 
And execute: /opt/activemq/bin/activemq browse --amqurl tcp://localhost:61616 MYQUEUE without any credentials

To fix: I think you have to add in activemq.xml a section as described in one of these links:  
- https://activemq.apache.org/security   
- http://svn.apache.org/repos/asf/activemq/trunk/activemq-unit-tests/src/test/resources/org/apache/activemq/security/jaas-broker.xml

**Comment by tholu** [comment]
@sconstro Can you add more details on how to reproduce the issue?

**Comment by sconstro** [comment]
@tholu  Done

**Comment by tholu** [comment]
@sconstro Thanks, I can reproduce the issue - the `credentials.properties` is not recognized (anymore).

**Comment by apexbb** [comment]
So no more update/fix for the Security for 5.18.3 ?

**Comment by tholu** [comment]
@apexbb Didn't have time to look at it yet, but there will be an update/fix for 5.18.3.

**Comment by tholu** [comment]
@sconstro Fixed with the 5.18.4 release.
