### ISSUE TITLE
Configure jetty / logging dynamically based on env vars

### ISSUE THREAD

**Issue by robertoschwald** [symptoma/activemq#6]
It would be great to be able to configure jetty by env-vars instead of mapping in a modified jetty.xml file ( see #4)
e.g.
* jetty host property 
* jetty port property
* log4j2 settings (currently some logging is performed to data/activemq.log and data/audit.log), so an env var setting to log everything to console would be helpful. 

This way, it would be easy to run e.g. in Amazon ECS or any other container service.

Modifications may be performed e.g. by using an entrypoint script which performs the necessary changes in conf/jetty.xml and conf/log4j2.properties

**Comment by tholu** [comment]
@robertoschwald Totally agree! Would you like to provide a pull request for this? Side note: ActiveMQ plans to provide an official container as well, but I'm not sure if they have done so already.

**Comment by robertoschwald** [comment]
I will provide a PR. As it is based on Alpine, I will use shell / sed for the modifications to keep the image small.

**Comment by tholu** [comment]
@robertoschwald Merged and released on Docker Hub - thanks again!
